In [2]:
import numpy as np
import pandas as pd

In [15]:
#A series is a 1D array containing data of the same type
s1 =pd.Series(np.random.randn(10))

In [10]:
s2=pd.Series([20,30,40,50],name="age",index=range(4))

In [11]:
s2

0    20
1    30
2    40
3    50
Name: age, dtype: int64

In [12]:
s3=pd.Series(["dan","liya","makena","kendi"],name="family",index=["a","b","c","d"])

In [13]:
s3

a       dan
b      liya
c    makena
d     kendi
Name: family, dtype: object

In [16]:
s1.index

RangeIndex(start=0, stop=10, step=1)

In [17]:
s3.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [19]:
s3["a"]

'dan'

In [21]:
#Slicing a pandas series, i.e. it is upper bound limit
s1[1:4]

1   -1.518262
2   -0.223698
3   -0.417598
dtype: float64

In [25]:
#return multiple items by specifying the index
s1[[1,2,3]]

1   -1.518262
2   -0.223698
3   -0.417598
dtype: float64

In [26]:
s1.mean()

-0.10039835487659277

In [27]:
s1

0   -0.489408
1   -1.518262
2   -0.223698
3   -0.417598
4   -0.169446
5   -0.845336
6    1.496357
7   -0.641578
8    1.429631
9    0.375355
dtype: float64

In [28]:
s1.median()

-0.320647918936556

In [32]:
s1[s1>0]

6    1.496357
8    1.429631
9    0.375355
dtype: float64

In [33]:
s1.mean()

-0.10039835487659277

In [34]:
s1 = s1*2

In [35]:
s1

0   -0.978817
1   -3.036524
2   -0.447395
3   -0.835196
4   -0.338893
5   -1.690672
6    2.992714
7   -1.283156
8    2.859261
9    0.750711
dtype: float64

In [36]:
s1.dtype

dtype('float64')

In [39]:
reviews = pd.read_csv("wine reviews.csv",index_col=0)

In [40]:
reviews.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [41]:
reviews.columns

Index(['country', 'description', 'designation', 'points', 'price', 'province',
       'region_1', 'region_2', 'taster_name', 'taster_twitter_handle', 'title',
       'variety', 'winery'],
      dtype='object')

In [42]:
reviews.index

Int64Index([     0,      1,      2,      3,      4,      5,      6,      7,
                 8,      9,
            ...
            129961, 129962, 129963, 129964, 129965, 129966, 129967, 129968,
            129969, 129970],
           dtype='int64', length=129971)

In [44]:
reviews.shape

(129971, 13)

In [46]:
reviews.dtypes

country                   object
description               object
designation               object
points                     int64
price                    float64
province                  object
region_1                  object
region_2                  object
taster_name               object
taster_twitter_handle     object
title                     object
variety                   object
winery                    object
dtype: object

In [48]:
reviews.head(n=10)

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
5,Spain,Blackberry and raspberry aromas show a typical...,Ars In Vitro,87,15.0,Northern Spain,Navarra,NaN,Michael Schachner,@wineschach,Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...,Tempranillo-Merlot,Tandem
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
7,France,This dry and restrained wine offers spice in p...,NaN,87,24.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Trimbach 2012 Gewurztraminer (Alsace),Gewürztraminer,Trimbach
8,Germany,Savory dried thyme notes accent sunnier flavor...,Shine,87,12.0,Rheinhessen,NaN,NaN,Anna Lee C. Iijima,NaN,Heinz Eifel 2013 Shine Gewürztraminer (Rheinhe...,Gewürztraminer,Heinz Eifel
9,France,This has great depth of flavor with its fresh ...,Les Natures,87,27.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Jean-Baptiste Adam 2012 Les Natures Pinot Gris...,Pinot Gris,Jean-Baptiste Adam

In [49]:
reviews.describe()

              points          price
count  129971.000000  120975.000000
mean       88.447138      35.363389
std         3.039730      41.022218
min        80.000000       4.000000
25%        86.000000      17.000000
50%        88.000000      25.000000
75%        91.000000      42.000000
max       100.000000    3300.000000

In [53]:
count = reviews.country

In [55]:
count.dtypes

dtype('O')

In [56]:
reviews.description

0         Aromas include tropical fruit, broom, brimston...
1         This is ripe and fruity, a wine that is smooth...
2         Tart and snappy, the flavors of lime flesh and...
3         Pineapple rind, lemon pith and orange blossom ...
4         Much like the regular bottling from 2012, this...
5         Blackberry and raspberry aromas show a typical...
6         Here's a bright, informal red that opens with ...
7         This dry and restrained wine offers spice in p...
8         Savory dried thyme notes accent sunnier flavor...
9         This has great depth of flavor with its fresh ...
10        Soft, supple plum envelopes an oaky structure ...
11        This is a dry wine, very spicy, with a tight, ...
12        Slightly reduced, this wine offers a chalky, t...
13        This is dominated by oak and oak-driven aromas...
14        Building on 150 years and six generations of w...
15        Zesty orange peels and apple notes abound in t...
16        Baked plum, molasses, balsamic vinegar and che...
17        Raw black-cherry aromas are direct and simple ...
18        Desiccated blackberry, leather, charred wood a...
19        Red fruit aromas pervade on the nose, with cig...
20        Ripe aromas of dark berries mingle with ample ...
21        A sleek mix of tart berry, stem and herb, alon...
22        Delicate aromas recall white flower and citrus...
23        This wine from the Geneseo district offers aro...
24        Aromas of prune, blackcurrant, toast and oak c...
25        Oak and earth intermingle around robust aromas...
26        Pretty aromas of yellow flower and stone fruit...
27        Aromas recall ripe dark berry, toast and a whi...
28        Aromas suggest mature berry, scorched earth, a...
29        Clarksburg is becoming a haven for Chenin Blan...
                                ...
129941    A Chardonnay with an unusual companion, 8% Sém...
129942    This is classic in herbaceous aromas and flavo...
129943    A blend of Nero d'Avola and Syrah, this convey...
129944    Deep garnet in the glass, this has a nose of b...
129945    Hailing from one of the more popular vineyards...
129946    Plump, clingy peach and honey notes are cut wi...
129947    A blend of 65% Cabernet Sauvignon, 30% Merlot ...
129948    Raspberry and cassis aromas are fresh and upri...
129949    There's no bones about the use of oak in this ...
129950    This opens with herbaceous dollops of thyme an...
129951    Hugely spicy this rich wine is described as sw...
129952    This Zinfandel from the eastern section of Nap...
129953    Roughly two-thirds Cabernet and one-third Merl...
129954    One of the more characterful Pinot Gris for th...
129955    Like Dog Point's 2011 Chardonnay, this wine is...
129956    The blend is 44% Merlot, 33% Cabernet Sauvigno...
129957    Lightly baked berry aromas vie for attention w...
129958    This blend of Cabernet Sauvignon-Merlot and Ca...
129959    The granite soil of the Brand Grand Cru vineya...
129960    Fresh and fruity, this is full of red cherry f...
129961    Intense aromas of wild cherry, baking spice, t...
129962    Blackberry, cassis, grilled herb and toasted a...
129963    A bouquet of black cherry, tart cranberry and ...
129964    Initially quite muted, this wine slowly develo...
129965    While it's rich, this beautiful dry wine also ...
129966    Notes of honeysuckle and cantaloupe sweeten th...
129967    Citation is given as much as a decade of bottl...
129968    Well-drained gravel soil gives this wine its c...
129969    A dry style of Pinot Gris, this is crisp with ...
129970    Big, rich and off-dry, this is powered by inte...
Name: description, Length: 129971, dtype: object

In [57]:
#selecting multiple columns
reviews[0:10]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
5,Spain,Blackberry and raspberry aromas show a typical...,Ars In Vitro,87,15.0,Northern Spain,Navarra,NaN,Michael Schachner,@wineschach,Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...,Tempranillo-Merlot,Tandem
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
7,France,This dry and restrained wine offers spice in p...,NaN,87,24.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Trimbach 2012 Gewurztraminer (Alsace),Gewürztraminer,Trimbach
8,Germany,Savory dried thyme notes accent sunnier flavor...,Shine,87,12.0,Rheinhessen,NaN,NaN,Anna Lee C. Iijima,NaN,Heinz Eifel 2013 Shine Gewürztraminer (Rheinhe...,Gewürztraminer,Heinz Eifel
9,France,This has great depth of flavor with its fresh ...,Les Natures,87,27.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Jean-Baptiste Adam 2012 Les Natures Pinot Gris...,Pinot Gris,Jean-Baptiste Adam

In [58]:
reviews[0:10:2]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
8,Germany,Savory dried thyme notes accent sunnier flavor...,Shine,87,12.0,Rheinhessen,NaN,NaN,Anna Lee C. Iijima,NaN,Heinz Eifel 2013 Shine Gewürztraminer (Rheinhe...,Gewürztraminer,Heinz Eifel

In [60]:
reviews.loc[1]

country                                                           Portugal
description              This is ripe and fruity, a wine that is smooth...
designation                                                       Avidagos
points                                                                  87
price                                                                   15
province                                                             Douro
region_1                                                               NaN
region_2                                                               NaN
taster_name                                                     Roger Voss
taster_twitter_handle                                           @vossroger
title                        Quinta dos Avidagos 2011 Avidagos Red (Douro)
variety                                                     Portuguese Red
winery                                                 Quinta dos Avidagos
Name: 1, dtype: object

In [62]:
reviews.iloc[:5]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [63]:
reviews.country.loc[:10]

0        Italy
1     Portugal
2           US
3           US
4           US
5        Spain
6        Italy
7       France
8      Germany
9       France
10          US
Name: country, dtype: object

In [67]:
reviews.country.head([2:7])

SyntaxError: invalid syntax (<ipython-input-67-5a7a5d6b42ff>, line 1)

In [70]:
reviews[["description","country"]].loc[[1,2,3,4]]

                                         description   country
1  This is ripe and fruity, a wine that is smooth...  Portugal
2  Tart and snappy, the flavors of lime flesh and...        US
3  Pineapple rind, lemon pith and orange blossom ...        US
4  Much like the regular bottling from 2012, this...        US

In [72]:
ser = pd.Series(data=["Jabez","Nzomo"], index=["One","two"])

In [73]:
ser

One    Jabez
two    Nzomo
dtype: object

In [77]:
ser.iloc[1]

'Nzomo'

In [80]:
reviews[["description","country"]][0:100].tail()

                                          description country
95  This is a dense wine, packed with both tannins...  France
96  The wine comes from one of the cru estates fol...  France
97  A wisp of bramble extends a savory tone from n...      US
98  Forest floor, menthol, espresso, cranberry and...   Italy
99  This blends 20% each of all five red-Bordeaux ...      US

In [81]:
reviews[["description","country"]].loc[:100]

                                           description    country
0    Aromas include tropical fruit, broom, brimston...      Italy
1    This is ripe and fruity, a wine that is smooth...   Portugal
2    Tart and snappy, the flavors of lime flesh and...         US
3    Pineapple rind, lemon pith and orange blossom ...         US
4    Much like the regular bottling from 2012, this...         US
5    Blackberry and raspberry aromas show a typical...      Spain
6    Here's a bright, informal red that opens with ...      Italy
7    This dry and restrained wine offers spice in p...     France
8    Savory dried thyme notes accent sunnier flavor...    Germany
9    This has great depth of flavor with its fresh ...     France
10   Soft, supple plum envelopes an oaky structure ...         US
11   This is a dry wine, very spicy, with a tight, ...     France
12   Slightly reduced, this wine offers a chalky, t...         US
13   This is dominated by oak and oak-driven aromas...      Italy
14   Building on 150 years and six generations of w...         US
15   Zesty orange peels and apple notes abound in t...    Germany
16   Baked plum, molasses, balsamic vinegar and che...  Argentina
17   Raw black-cherry aromas are direct and simple ...  Argentina
18   Desiccated blackberry, leather, charred wood a...      Spain
19   Red fruit aromas pervade on the nose, with cig...         US
20   Ripe aromas of dark berries mingle with ample ...         US
21   A sleek mix of tart berry, stem and herb, alon...         US
22   Delicate aromas recall white flower and citrus...      Italy
23   This wine from the Geneseo district offers aro...         US
24   Aromas of prune, blackcurrant, toast and oak c...      Italy
25   Oak and earth intermingle around robust aromas...         US
26   Pretty aromas of yellow flower and stone fruit...      Italy
27   Aromas recall ripe dark berry, toast and a whi...      Italy
28   Aromas suggest mature berry, scorched earth, a...      Italy
29   Clarksburg is becoming a haven for Chenin Blan...         US
..                                                 ...        ...
71   Big oak defines this robustly dense and extrac...         US
72   Aromas of black-skinned fruit, leather, underb...      Italy
73   Juicy plum, raspberry and pencil lead lead the...         US
74   This is the producer's first release of this w...         US
75   This is made from equal parts Cabernet Franc a...         US
76   Earthy pollen and mineral notes lend a savory ...    Germany
77   This medium-bodied Chardonnay features aromas ...  Australia
78   Some rosés are made simply by bleeding the jui...         US
79   Grown on the sandy soil of Tejo, the wine is t...   Portugal
80   Caramelized oak and vanilla aromas are front a...      Chile
81   Bland, mature aromas of white fruits are on th...      Spain
82   This fruity, sweet wine is immediately attract...     France
83   Pale copper in hue, this wine exudes passion f...  Australia
84   A healthy addition of 13% Petite Sirah provide...         US
85   Pronounced dust, pollen and earth tones lend s...    Germany
86   Vibrant aromas of ripe pear, white flowers and...         US
87   Softened tannins surround a light-bodied, lean...         US
88   Subdued aromas of French oak, toast and acacia...      Italy
89   Made primarily from Sangiovese, with some Malv...      Italy
90   This blend of Sangiovese, Malbec, Cabernet Sau...         US
91   This wine has a touch of perceptible sweetness...         US
92   All red Bordeaux varieties are represented in ...         US
93   Freshness characterizes the nose: green pear, ...    Austria
94   Barrel notes are prominent, with aromas of Cre...         US
95   This is a dense wine, packed with both tannins...     France
96   The wine comes from one of the cru estates fol...     France
97   A wisp of bramble extends a savory tone from n...         US
98   Forest floor, menthol, espresso, cranberry and...      Italy
99   This blends 20% each of all five red-Bordeaux ...         US
100  Fresh apple, lemon and pear flavors are accent...         US

[101 rows x 2 columns]

In [87]:
reviews[[:100]]

SyntaxError: invalid syntax (<ipython-input-87-eb0d8c1b0f22>, line 1)

In [95]:
reviews.loc[reviews.country=="Italy",["price"]]

        price
0         NaN
6        16.0
13        NaN
22       19.0
24       35.0
26       13.0
27       10.0
28       17.0
31        NaN
32        NaN
37       21.0
38       11.0
39       12.0
40       17.0
46       13.0
50        NaN
52       14.0
54        NaN
57       13.0
61       17.0
72       32.0
88       29.0
89       19.0
98       30.0
104      16.0
105      14.0
106      30.0
107      18.0
109      30.0
112      15.0
...       ...
129740   45.0
129750   18.0
129760   25.0
129778   80.0
129795   55.0
129797   26.0
129801   36.0
129803   50.0
129804   25.0
129807    NaN
129809   62.0
129813    NaN
129819   75.0
129822   45.0
129824   85.0
129826   50.0
129842   12.0
129843   18.0
129844    NaN
129849   20.0
129850   24.0
129851   10.0
129852   10.0
129892   72.0
129893    NaN
129929   38.0
129943   29.0
129947   20.0
129961   30.0
129962   40.0

[19540 rows x 1 columns]

In [96]:
reviews.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [101]:
reviews.loc[reviews.country == "Italy",["price","country"]]

        price country
0         NaN   Italy
6        16.0   Italy
13        NaN   Italy
22       19.0   Italy
24       35.0   Italy
26       13.0   Italy
27       10.0   Italy
28       17.0   Italy
31        NaN   Italy
32        NaN   Italy
37       21.0   Italy
38       11.0   Italy
39       12.0   Italy
40       17.0   Italy
46       13.0   Italy
50        NaN   Italy
52       14.0   Italy
54        NaN   Italy
57       13.0   Italy
61       17.0   Italy
72       32.0   Italy
88       29.0   Italy
89       19.0   Italy
98       30.0   Italy
104      16.0   Italy
105      14.0   Italy
106      30.0   Italy
107      18.0   Italy
109      30.0   Italy
112      15.0   Italy
...       ...     ...
129740   45.0   Italy
129750   18.0   Italy
129760   25.0   Italy
129778   80.0   Italy
129795   55.0   Italy
129797   26.0   Italy
129801   36.0   Italy
129803   50.0   Italy
129804   25.0   Italy
129807    NaN   Italy
129809   62.0   Italy
129813    NaN   Italy
129819   75.0   Italy
129822   45.0   Italy
129824   85.0   Italy
129826   50.0   Italy
129842   12.0   Italy
129843   18.0   Italy
129844    NaN   Italy
129849   20.0   Italy
129850   24.0   Italy
129851   10.0   Italy
129852   10.0   Italy
129892   72.0   Italy
129893    NaN   Italy
129929   38.0   Italy
129943   29.0   Italy
129947   20.0   Italy
129961   30.0   Italy
129962   40.0   Italy

[19540 rows x 2 columns]

In [104]:
reviews.loc[(reviews.points >= 95) & (reviews.country.isin(["Australia","New Zealand"])),["description"]]

                                              description
345     This wine contains some material over 100 year...
346     This deep brown wine smells like a damp, mossy...
348     Deep mahogany. Dried fig and black tea on the ...
349     RunRig is always complex, and the 2012 doesn't...
356     Dusty, firm, powerful: just a few apt descript...
360     Bacon and tapenade elements merge easily on th...
365     The Taylor family selected Clare Valley for it...
14354   This wine's concentrated dark fruit shows in t...
16538   Rich, dense and intense, this is a big, muscul...
28573   Astralis has become one of Australia's top col...
34502   This prodigious wine showcases Barossa's abili...
34506   If Standish's Relic is the feminine side of Sh...
38988   Penfolds Bin 707 has leapt in quality over the...
39059   The Taylor family selected Clare Valley for it...
39961   As unevolved as they are, the dense and multil...
39962   Seamless luxury from stem to stern, this ‘baby...
45809   The 2007 Astralis impresses for its combinatio...
56953   This inky, embryonic wine deserves to be cella...
56956   You may have to scour the country to secure so...
56957   Thorn Clarke has taken its Shiraz to a new lev...
56959   Is this the Yin to Grange's Yang? The wines ar...
59977   This is a top example of the classic Australia...
59984   This is a throwback to those brash, flavor-exu...
67096   Just a tiny serving of this dark nectar will l...
67101   This Muscat is the color of dark coffee, with ...
76392   When the alcohol levels are reined in to appro...
77028   This has all the size and weight you've come t...
77036   RWT (unromantically derived from “Red Wine Tri...
77037   Winemaker Dave Powell is no longer with Torbre...
77042   This is likely the most ageworthy Shiraz winem...
77044   The fruit for this offering comes from the Gre...
77046   With aromas and flavors that range widely from...
83357   A throwback to the monster Shiraz style of old...
84815   The Factor is always one of Torbreck's biggest...
84816   Nashwauk is Kaesler's McLaren Vale project, fi...
87128   This full-bodied, muscular Shiraz is built for...
87137   Perhaps the best young wine I've tasted from M...
87143   This is wonderfully complex and aromatic, with...
91851   This full-bodied, richly tannic wine delivers....
98386   One of the more approachable of the d'Arenberg...
99318   From vines planted in 1912, this has been an i...
99330   This Cabernet equivalent to Grange has explode...
99340   This rich, opulent wine carries its massive oa...
109427  This wine is dark brown in hue with a greenish...
109434  D'Arenberg's lineup of single-vineyard Shiraze...
122421  Despite this wine's weight and richness, it re...
122430  These blends are traditional in Australia—they...
122507  This blend of Cabernet Sauvignon (62.5%), Merl...
122939  Full-bodied and plush yet vibrant and imbued w...

In [106]:
reviews.loc[(reviews.price >100),["description"]]

                                              description
139     Beautiful deep gold color. Intense, concentrat...
284     This huge Malbec defines jammy and concentrate...
289     This 100% Cabernet Sauvignon is so rich and de...
345     This wine contains some material over 100 year...
346     This deep brown wine smells like a damp, mossy...
347     Dusty, saffron-spiced earthiness is juxtaposed...
349     RunRig is always complex, and the 2012 doesn't...
350     After a few minutes in the glass, this stunnin...
351     This amber-colored Hungarian stunner has ether...
353     This beautiful, rich wine has yellow fruits an...
354     Whiffs of white mushroom, saffron and caramel ...
357     Produced from vines more than 100 years old in...
359     Up the slope above the Grand Cru of Le Montrac...
360     Bacon and tapenade elements merge easily on th...
362     As impressive as the woman—a pioneer in the Na...
363     This is an opulent wine from one of the fabled...
370     Mint again, with earth and tobacco; one taster...
464     Richly textured and unabashedly full in body, ...
475     This 100% Cabernet Sauvignon was grown in the ...
537     A 100% varietal wine, this offers upfront stru...
547     Deep aromas of dried strawberries and blueberr...
636     The Torbreck wines, with the emphasis they pla...
710     As typical for Dry River Pinots, this one is p...
739     Roasted coffee bean and menthol aromas lead th...
778     The Winderlea is perhaps the most unique in te...
779     This is a powerful, almost concentrated, very ...
787     Robust black fruit forms around a dense, leath...
810     This wine opens with a confectionary nose, slo...
850     Young vines, planted in 2007, give a fresh, fr...
859     This is a generous, leathery and tannic wine, ...
...                                                   ...
128759  A light touch is put on this elegant wine, one...
128830  A blend of almost equal parts Cabernet Sauvign...
128850  This wine backs up the price tag with a fruit-...
128906  With 15.4% alcohol by volume, this is arguably...
128948  This ambitious effort stars flavors so ripe an...
128979  Aromas of woodspice, cedar, cranberry and cher...
128986  Abundantly rich in fruit, this Cabernet shows ...
128991  A pinch of hard tannins gives this bone-dry yo...
128996  Few Bordeaux-style wines in California are as ...
129052  Aged for at least five years in the Lanson cel...
129060  This prestige cuvée from Collet, with its hand...
129141  This is obviously a beautiful Cabernet Sauvign...
129235  Ripe and structured, this has black plum and r...
129243  A mere 40 cases of this LD exists, a lucky fin...
129251  Aromas of spice, vanilla and wood are stronger...
129293  Brawny tannins meet mild acidity in this power...
129294  With round clove and dried herb flavors, this ...
129298  Rich as chocolate cake, this bold wine is ador...
129549  Minty cedar rides atop an expansive succulence...
129559  This wine is a blend of 79% Cabernet Sauvignon...
129666  Classically powerful and rich, this is a conce...
129667  With spice and layers of wood aging over the b...
129668  A level portion of this premier cru, called Le...
129686  This vineyard is at the heart of the fine run ...
129717  Leathery, thick and densely concentrated, this...
129725  This robust wine is made from 62% Merlot, 37% ...
129729  Bold oak on the nose places aromas of hickory ...
129818  Concentrated, with dark tannins to go with the...
129919  This ripe, rich, almost decadently thick wine ...
129931  A powerful, chunky wine, packed with solid tan...

[3366 rows x 1 columns]

In [107]:
reviews.loc[:100,["country","price"]]

       country  price
0        Italy    NaN
1     Portugal   15.0
2           US   14.0
3           US   13.0
4           US   65.0
5        Spain   15.0
6        Italy   16.0
7       France   24.0
8      Germany   12.0
9       France   27.0
10          US   19.0
11      France   30.0
12          US   34.0
13       Italy    NaN
14          US   12.0
15     Germany   24.0
16   Argentina   30.0
17   Argentina   13.0
18       Spain   28.0
19          US   32.0
20          US   23.0
21          US   20.0
22       Italy   19.0
23          US   22.0
24       Italy   35.0
25          US   69.0
26       Italy   13.0
27       Italy   10.0
28       Italy   17.0
29          US   16.0
..         ...    ...
71          US   40.0
72       Italy   32.0
73          US   75.0
74          US   55.0
75          US   75.0
76     Germany    9.0
77   Australia   18.0
78          US   25.0
79    Portugal    NaN
80       Chile   12.0
81       Spain   16.0
82      France   11.0
83   Australia   20.0
84          US   24.0
85     Germany   10.0
86          US   20.0
87          US   55.0
88       Italy   29.0
89       Italy   19.0
90          US   23.0
91          US   18.0
92          US   55.0
93     Austria   12.0
94          US   22.0
95      France   20.0
96      France   18.0
97          US   20.0
98       Italy   30.0
99          US   75.0
100         US   18.0

[101 rows x 2 columns]

In [108]:
reviews[["price","country"]].iloc[:100]

    price    country
0     NaN      Italy
1    15.0   Portugal
2    14.0         US
3    13.0         US
4    65.0         US
5    15.0      Spain
6    16.0      Italy
7    24.0     France
8    12.0    Germany
9    27.0     France
10   19.0         US
11   30.0     France
12   34.0         US
13    NaN      Italy
14   12.0         US
15   24.0    Germany
16   30.0  Argentina
17   13.0  Argentina
18   28.0      Spain
19   32.0         US
20   23.0         US
21   20.0         US
22   19.0      Italy
23   22.0         US
24   35.0      Italy
25   69.0         US
26   13.0      Italy
27   10.0      Italy
28   17.0      Italy
29   16.0         US
..    ...        ...
70   12.0         US
71   40.0         US
72   32.0      Italy
73   75.0         US
74   55.0         US
75   75.0         US
76    9.0    Germany
77   18.0  Australia
78   25.0         US
79    NaN   Portugal
80   12.0      Chile
81   16.0      Spain
82   11.0     France
83   20.0  Australia
84   24.0         US
85   10.0    Germany
86   20.0         US
87   55.0         US
88   29.0      Italy
89   19.0      Italy
90   23.0         US
91   18.0         US
92   55.0         US
93   12.0    Austria
94   22.0         US
95   20.0     France
96   18.0     France
97   20.0         US
98   30.0      Italy
99   75.0         US

[100 rows x 2 columns]

In [109]:
reviews.iloc[:100,[0,4]]

      country  price
0       Italy    NaN
1    Portugal   15.0
2          US   14.0
3          US   13.0
4          US   65.0
5       Spain   15.0
6       Italy   16.0
7      France   24.0
8     Germany   12.0
9      France   27.0
10         US   19.0
11     France   30.0
12         US   34.0
13      Italy    NaN
14         US   12.0
15    Germany   24.0
16  Argentina   30.0
17  Argentina   13.0
18      Spain   28.0
19         US   32.0
20         US   23.0
21         US   20.0
22      Italy   19.0
23         US   22.0
24      Italy   35.0
25         US   69.0
26      Italy   13.0
27      Italy   10.0
28      Italy   17.0
29         US   16.0
..        ...    ...
70         US   12.0
71         US   40.0
72      Italy   32.0
73         US   75.0
74         US   55.0
75         US   75.0
76    Germany    9.0
77  Australia   18.0
78         US   25.0
79   Portugal    NaN
80      Chile   12.0
81      Spain   16.0
82     France   11.0
83  Australia   20.0
84         US   24.0
85    Germany   10.0
86         US   20.0
87         US   55.0
88      Italy   29.0
89      Italy   19.0
90         US   23.0
91         US   18.0
92         US   55.0
93    Austria   12.0
94         US   22.0
95     France   20.0
96     France   18.0
97         US   20.0
98      Italy   30.0
99         US   75.0

[100 rows x 2 columns]

In [113]:
reviews[["country","price"]][0:100]

      country  price
0       Italy    NaN
1    Portugal   15.0
2          US   14.0
3          US   13.0
4          US   65.0
5       Spain   15.0
6       Italy   16.0
7      France   24.0
8     Germany   12.0
9      France   27.0
10         US   19.0
11     France   30.0
12         US   34.0
13      Italy    NaN
14         US   12.0
15    Germany   24.0
16  Argentina   30.0
17  Argentina   13.0
18      Spain   28.0
19         US   32.0
20         US   23.0
21         US   20.0
22      Italy   19.0
23         US   22.0
24      Italy   35.0
25         US   69.0
26      Italy   13.0
27      Italy   10.0
28      Italy   17.0
29         US   16.0
..        ...    ...
70         US   12.0
71         US   40.0
72      Italy   32.0
73         US   75.0
74         US   55.0
75         US   75.0
76    Germany    9.0
77  Australia   18.0
78         US   25.0
79   Portugal    NaN
80      Chile   12.0
81      Spain   16.0
82     France   11.0
83  Australia   20.0
84         US   24.0
85    Germany   10.0
86         US   20.0
87         US   55.0
88      Italy   29.0
89      Italy   19.0
90         US   23.0
91         US   18.0
92         US   55.0
93    Austria   12.0
94         US   22.0
95     France   20.0
96     France   18.0
97         US   20.0
98      Italy   30.0
99         US   75.0

[100 rows x 2 columns]

In [114]:
reviews.country.unique()

array(['Italy', 'Portugal', 'US', 'Spain', 'France', 'Germany',
       'Argentina', 'Chile', 'Australia', 'Austria', 'South Africa',
       'New Zealand', 'Israel', 'Hungary', 'Greece', 'Romania', 'Mexico',
       'Canada', nan, 'Turkey', 'Czech Republic', 'Slovenia',
       'Luxembourg', 'Croatia', 'Georgia', 'Uruguay', 'England',
       'Lebanon', 'Serbia', 'Brazil', 'Moldova', 'Morocco', 'Peru',
       'India', 'Bulgaria', 'Cyprus', 'Armenia', 'Switzerland',
       'Bosnia and Herzegovina', 'Ukraine', 'Slovakia', 'Macedonia',
       'China', 'Egypt'], dtype=object)

In [120]:
countries = reviews.country.unique()

In [122]:
reviews.country.value_counts()

US                        54504
France                    22093
Italy                     19540
Spain                      6645
Portugal                   5691
Chile                      4472
Argentina                  3800
Austria                    3345
Australia                  2329
Germany                    2165
New Zealand                1419
South Africa               1401
Israel                      505
Greece                      466
Canada                      257
Hungary                     146
Bulgaria                    141
Romania                     120
Uruguay                     109
Turkey                       90
Slovenia                     87
Georgia                      86
England                      74
Croatia                      73
Mexico                       70
Moldova                      59
Brazil                       52
Lebanon                      35
Morocco                      28
Peru                         16
Ukraine                      14
Macedonia                    12
Czech Republic               12
Serbia                       12
Cyprus                       11
India                         9
Switzerland                   7
Luxembourg                    6
Armenia                       2
Bosnia and Herzegovina        2
Egypt                         1
Slovakia                      1
China                         1
Name: country, dtype: int64

In [123]:
ratio = reviews.points / reviews.price

In [124]:
bargain = ratio.idxmax

In [126]:
reviews.loc[bargain,["title","country"]]

title      Bandit NV Merlot (California)
country                               US
Name: 64590, dtype: object